### ISSUE TITLE
ExecutorDao fails to update expires timestamp due to saylight saving time

### ISSUE THREAD

**Issue by efonsell** [NitorCreations/nflow#217]
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [update nflow_executor set active=current_timestamp, expires=date_add(current_timestamp, interval 900 second) where id = 90]; Data truncation: Incorrect datetime value: '2017-
03-26 03:14:38.000' for column 'expires' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '2017-03-26 03:14:38.000' for column 'expires' at row 1
at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:102)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:870)
at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:931)
at io.nflow.engine.internal.dao.ExecutorDao.updateWithPreparedStatement(ExecutorDao.java:157)
at io.nflow.engine.internal.dao.ExecutorDao.updateActiveTimestamp(ExecutorDao.java:151)
at io.nflow.engine.internal.dao.ExecutorDao.tick(ExecutorDao.java:92)

**Comment by efonsell** [comment]
https://github.com/NitorCreations/nflow/pull/218
