### ISSUE TITLE
Batch operation exception while running nflow application on nflow version 4.2.0

### ISSUE THREAD

**Issue by goyalneeraj18** [NitorCreations/nflow#375]
I have my application which was earlier running on nflow 4.0.0, Now i have upgrade this 4.2.0 as i need to use some of the current classes which is created in another application which is already running in 4.2.0.

While running the application first i got issue for column workflow_signal does not found in nflow_workflow table.
I have already below script in my nflow database.
https://github.com/NitorCreations/nflow/blob/master/nflow-engine/src/main/resources/scripts/db/update-4.0.0-x/mysql.update.ddl.sql

So i am stuck with an issue where while running my application it starts to give me  error as per below screenshot.

![image](https://user-images.githubusercontent.com/12641617/73540512-cd36cf00-4438-11ea-9d43-d7ebe6788ea9.png)

Here are some logs

2020-01-31 13:13:35 INFO  [nflow-dispatcher] al.executor.WorkflowDispatcher - [] Starting.
2020-01-31 13:13:35 ERROR [nflow-dispatcher] al.executor.WorkflowDispatcher - [] Exception in executing dispatcher - retrying after sleep period (PreparedStatementCallback; uncategorized SQLException for SQL [update nflow_workflow set executor_id = 525, status = 'executing', external_next_activation = null where id = ? and modified = ? and executor_id is null]; SQL state [HY000]; error code [4033]; (conn=2357999) Only row based replication supported for bulk operations; nested exception is java.sql.BatchUpdateException: (conn=2357999) Only row based replication supported for bulk operations)
org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [update nflow_workflow set executor_id = 525, status = 'executing', external_next_activation = null where id = ? and modified = ? and executor_id is null]; SQL state [HY000]; error code [4033]; (conn=2357999) Only row based replication supported for bulk operations; nested exception is java.sql.BatchUpdateException: (conn=2357999) Only row based replication supported for bulk operations
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:84)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:649)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:662)
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:950)
	at org.springframework.jdbc.core.BatchUpdateUtils.executeBatchUpdate(BatchUpdateUtils.java:32)
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:1000)

My current database version is 
ysql  Ver 15.1 Distrib 10.1.13-MariaDB,

I am using driver com.mysql.jdbc.Driver

I can try to upgrade my nflow application on latest version but i need to still analyze  about the efforts needed and challenges.

**Comment by efonsell** [comment]
Property to disable batch updates (setting nflow.db.disable_batch_updates=true) was only added in 6.0.0, which is the first version to have "official" MariaDB support. It is a known issue that at least with Galera Cluster for MySQL, batch updates are not working. It is a bit strange though that batch updates were enabled for MySQL already in 4.0.0, so upgrading to 4.2.0 should have no effect on this.
Based on stack trace, you are using the MariaDB JDBC driver. You could try setting the DB url like this to avoid using the MariaDB JDBC driver even when it is found from classpath:
nflow.db.mysql.driver=com.mysql.jdbc.jdbc2.optional.MysqlDataSource
nflow.db.mysql.url=jdbc:mysql://<your-db-host:your-db-port>/nflow?disableMariaDbDriver
Updating the MySQL JDBC driver might also help.

**Comment by goyalneeraj18** [comment]
I am closing this issue as i found that this batch issue was happening as i am using some nflow engine class wrongly(i feel that), I am successfully able to upgrade my application on 4.2.0. Thanks for all your support. I will soon upgrade it in latest version.
