### ISSUE TITLE
jaxRsServer Bean error while nflow aplication is going to up

### ISSUE THREAD

**Issue by goyalneeraj18** [NitorCreations/nflow#384]
I am trying to test my nflow based application by junit which is hosted as a rest api and i am getting below error logs.
We are using nflow 4.2.0 as of now.

> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jaxRsServer' defined in class path resource [fi/eunet/conflow/NflowJettyConfigurationForConflow.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.cxf.endpoint.Server]: Factory method 'jaxRsServer' threw exception; nested exception is org.apache.cxf.service.factory.ServiceConstructionException
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)

**Comment by efonsell** [comment]
Cannot say anything based on this, the stack trace does not show any nFlow code. Have you checked StartNflow and NflowJettyConfiguration in nflow-jetty module for an example? Or AbstractNflowTest in nflow-tests module to see how it is set up in JUnit tests?

**Comment by efonsell** [comment]
Closing because not enough information to investigate further. Reopen or create a new issue with more info if needed.
