### ISSUE TITLE
jackson-core seems to be missing at runtime

### ISSUE THREAD

**Issue by mfdewit** [NitorCreations/nflow#448]
Hi,

I'm running a custom workflow using the plain Jetty runner (from the quickstart guide) like:
new StartNflow().startJetty(7500, "local", "");

When I use the nFLow Explorer to update the state I encounter the error below. It seems to be some classloading issue since it also worked on one occasion with the same config.

Tested on both version 7.2.4 and 7.3.0 on both Java 8 and 14. Same behaviour. 

2021-04-08 20:59:17 WARN  [qtp825658265-39] lipse.jetty.server.HttpChannel - [] /nflow/api/v1/workflow-instance/id/1
**java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/StreamReadCapability**
	at com.fasterxml.jackson.datatype.joda.deser.DateTimeDeserializer._fromString(DateTimeDeserializer.java:111)
	at com.fasterxml.jackson.datatype.joda.deser.DateTimeDeserializer.deserialize(DateTimeDeserializer.java:53)
	at com.fasterxml.jackson.datatype.joda.deser.DateTimeDeserializer.deserialize(DateTimeDeserializer.java:24)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2020)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1179)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:816)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBodyReader(JAXRSUtils.java:1430)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.readFromMessageBody(JAXRSUtils.java:1382)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.processRequestBodyParameter(JAXRSUtils.java:896)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.processParameters(JAXRSUtils.java:832)
	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:214)
	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:78)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPut(AbstractHTTPServlet.java:234)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.StreamReadCapability
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)

Output of maven dependency tree:

[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ nflow-test ---
[INFO] nl.scuro:nflow-test:jar:1.0-SNAPSHOT
[INFO] \- io.nflow:nflow-jetty:jar:7.2.4:compile
[INFO]    +- io.nflow:nflow-rest-api-jax-rs:jar:7.2.4:compile
[INFO]    |  +- io.nflow:nflow-rest-api-common:jar:7.2.4:compile
[INFO]    |  |  \- io.swagger:swagger-annotations:jar:1.6.2:compile
[INFO]    |  +- javax.ws.rs:javax.ws.rs-api:jar:2.1.1:compile
[INFO]    |  +- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO]    |  +- org.glassfish:javax.el:jar:3.0.0:runtime
[INFO]    |  \- org.hibernate.validator:hibernate-validator:jar:6.1.7.Final:compile
[INFO]    |     +- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO]    |     +- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
[INFO]    |     \- com.fasterxml:classmate:jar:1.3.4:compile
[INFO]    +- io.nflow:nflow-server-common:jar:7.2.4:compile
[INFO]    |  +- io.nflow:nflow-engine:jar:7.2.4:compile
[INFO]    |  |  +- org.springframework:spring-context:jar:5.2.8.RELEASE:compile
[INFO]    |  |  |  +- org.springframework:spring-aop:jar:5.2.8.RELEASE:compile
[INFO]    |  |  |  \- org.springframework:spring-expression:jar:5.2.8.RELEASE:compile
[INFO]    |  |  +- org.springframework:spring-jdbc:jar:5.2.8.RELEASE:compile
[INFO]    |  |  |  \- org.springframework:spring-tx:jar:5.2.8.RELEASE:compile
[INFO]    |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.0:compile
[INFO]    |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.12.0:compile
[INFO]    |  |  +- joda-time:joda-time:jar:2.10.8:compile
[INFO]    |  |  +- javax.inject:javax.inject:jar:1:compile
[INFO]    |  |  \- com.zaxxer:HikariCP:jar:3.4.5:compile
[INFO]    |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO]    |  +- org.slf4j:log4j-over-slf4j:jar:1.7.30:compile
[INFO]    |  +- org.slf4j:jcl-over-slf4j:jar:1.7.30:compile
[INFO]    |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO]    |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO]    |  \- org.slf4j:jul-to-slf4j:jar:1.7.30:compile
[INFO]    +- com.nitorcreations:core-utils:jar:1.4:compile
[INFO]    +- org.eclipse.jetty:jetty-server:jar:9.4.35.v20201120:compile
[INFO]    |  +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO]    |  +- org.eclipse.jetty:jetty-http:jar:9.4.35.v20201120:compile
[INFO]    |  \- org.eclipse.jetty:jetty-io:jar:9.4.35.v20201120:compile
[INFO]    +- org.eclipse.jetty:jetty-servlet:jar:9.4.35.v20201120:compile
[INFO]    |  +- org.eclipse.jetty:jetty-security:jar:9.4.35.v20201120:compile
[INFO]    |  \- org.eclipse.jetty:jetty-util-ajax:jar:9.4.35.v20201120:compile
[INFO]    +- org.eclipse.jetty:jetty-jmx:jar:9.4.35.v20201120:compile
[INFO]    |  \- org.eclipse.jetty:jetty-util:jar:9.4.35.v20201120:compile
[INFO]    +- org.apache.cxf:cxf-rt-frontend-jaxrs:jar:3.4.1:compile
[INFO]    |  +- org.apache.cxf:cxf-core:jar:3.4.1:compile
[INFO]    |  |  +- org.glassfish.jaxb:jaxb-runtime:jar:2.3.3:compile
[INFO]    |  |  |  +- org.glassfish.jaxb:txw2:jar:2.3.3:compile
[INFO]    |  |  |  \- com.sun.istack:istack-commons-runtime:jar:3.0.11:compile
[INFO]    |  |  +- com.fasterxml.woodstox:woodstox-core:jar:6.2.1:compile
[INFO]    |  |  |  \- org.codehaus.woodstox:stax2-api:jar:4.2.1:compile
[INFO]    |  |  +- org.apache.ws.xmlschema:xmlschema-core:jar:2.2.5:compile
[INFO]    |  |  \- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO]    |  +- jakarta.ws.rs:jakarta.ws.rs-api:jar:2.1.6:compile
[INFO]    |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO]    |  +- org.apache.cxf:cxf-rt-transports-http:jar:3.4.1:compile
[INFO]    |  +- org.apache.cxf:cxf-rt-security:jar:3.4.1:compile
[INFO]    |  +- jakarta.xml.ws:jakarta.xml.ws-api:jar:2.3.3:compile
[INFO]    |  +- jakarta.jws:jakarta.jws-api:jar:2.1.0:compile
[INFO]    |  +- jakarta.xml.soap:jakarta.xml.soap-api:jar:1.4.2:compile
[INFO]    |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO]    |  +- com.sun.activation:jakarta.activation:jar:1.2.2:compile
[INFO]    |  +- com.sun.xml.messaging.saaj:saaj-impl:jar:1.5.2:runtime
[INFO]    |  |  \- org.jvnet.staxex:stax-ex:jar:1.8.3:runtime
[INFO]    |  +- org.apache.geronimo.specs:geronimo-jta_1.1_spec:jar:1.1.1:compile
[INFO]    |  \- org.jboss.spec.javax.rmi:jboss-rmi-api_1.0_spec:jar:1.0.6.Final:compile
[INFO]    +- org.apache.cxf:cxf-rt-features-logging:jar:3.4.1:compile
[INFO]    +- org.apache.cxf:cxf-rt-management:jar:3.4.1:compile
[INFO]    +- org.apache.cxf:cxf-rt-rs-service-description-swagger:jar:3.4.1:compile
[INFO]    |  +- org.apache.cxf:cxf-rt-rs-service-description-common-openapi:jar:3.4.1:compile
[INFO]    |  \- org.apache.cxf:cxf-rt-rs-service-description-swagger-ui:jar:3.4.1:compile
[INFO]    +- io.swagger:swagger-jaxrs:jar:1.6.2:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.11.1:compile
[INFO]    |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.11.1:compile
[INFO]    |  +- io.swagger:swagger-core:jar:1.6.2:compile
[INFO]    |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.11.1:compile
[INFO]    |  |  |  \- org.yaml:snakeyaml:jar:1.26:compile
[INFO]    |  |  \- io.swagger:swagger-models:jar:1.6.2:compile
[INFO]    |  +- org.reflections:reflections:jar:0.9.11:compile
[INFO]    |  |  \- org.javassist:javassist:jar:3.21.0-GA:compile
[INFO]    |  \- com.google.guava:guava:jar:27.0.1-android:compile
[INFO]    |     +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO]    |     +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO]    |     +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO]    |     +- org.checkerframework:checker-compat-qual:jar:2.5.2:compile
[INFO]    |     +- com.google.errorprone:error_prone_annotations:jar:2.2.0:compile
[INFO]    |     +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO]    |     \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.17:compile
[INFO]    +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.12.0:compile
[INFO]    |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.12.0:compile
[INFO]    |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.12.0:compile
[INFO]    +- org.springframework:spring-web:jar:5.2.8.RELEASE:compile
[INFO]    |  +- org.springframework:spring-beans:jar:5.2.8.RELEASE:compile
[INFO]    |  \- org.springframework:spring-core:jar:5.2.8.RELEASE:compile
[INFO]    |     \- org.springframework:spring-jcl:jar:5.2.8.RELEASE:compile
[INFO]    +- org.apache.commons:commons-lang3:jar:3.11:compile
[INFO]    +- com.h2database:h2:jar:1.4.200:compile
[INFO]    +- io.dropwizard.metrics:metrics-servlets:jar:4.1.16:compile
[INFO]    |  +- io.dropwizard.metrics:metrics-core:jar:4.1.16:compile
[INFO]    |  +- io.dropwizard.metrics:metrics-healthchecks:jar:4.1.16:compile
[INFO]    |  +- io.dropwizard.metrics:metrics-json:jar:4.1.16:compile
[INFO]    |  +- io.dropwizard.metrics:metrics-jvm:jar:4.1.16:compile
[INFO]    |  \- com.helger:profiler:jar:1.1.1:compile
[INFO]    +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO]    |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO]    \- javax.xml.ws:jaxws-api:jar:2.3.1:compile
[INFO]       +- javax.xml.soap:javax.xml.soap-api:jar:1.4.0:compile
[INFO]       \- javax.annotation:javax.annotation-api:jar:1.3.2:compile

**Comment by efonsell** [comment]
StreamReadCapability was added to jackson-core in 2.12.0, but your dependency tree has jackson-core 2.11.1 for some reason. Jackson version in nFlow pom.xml is defined as 2.12.0, can you check if you override it or if there is something else that brings in 2.11.1?

**Comment by mfdewit** [comment]
The 2.11.1 version is a transitive dependency from swagger:

[INFO] +- io.swagger:swagger-jaxrs:jar:1.6.2:compile
[INFO] | +- com.fasterxml.jackson.core:jackson-databind:jar:2.11.1:compile
[INFO] | | - com.fasterxml.jackson.core:jackson-core:jar:2.11.1:compile

Somehow maven ignores the 2.12.0 version specified in the nFlow pom.xml and loads the older version. But as mentioned before, it did work 1 time. 

Anyway, my pom doesn't include any dependency besides nFlow itself. For the record:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>nl.scuro</groupId>
    <artifactId>nflow-test</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>14</maven.compiler.source>
        <maven.compiler.target>14</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>io.nflow</groupId>
            <artifactId>nflow-jetty</artifactId>
            <version>7.2.4</version>
        </dependency>
    </dependencies>
</project>

**Comment by efonsell** [comment]
Interesting, for me (tried with nFlow 7.2.4) Maven (3.6.1) resolves it to 2.12.0:
```
[INFO] +- io.swagger:swagger-jaxrs:jar:1.6.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.0:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.12.0:compile
```
Which Maven version you are using?

**Comment by efonsell** [comment]
You could also try adding an explicit dependency to the correct jackson-core version to your pom.xml

**Comment by mfdewit** [comment]
I'm using maven 3.6.3.
I've tried adding the explicit dependency as you mentioned and I get another error now:

java.lang.NoSuchMethodError: 'boolean com.fasterxml.jackson.databind.DeserializationContext.isEnabled(com.fasterxml.jackson.core.StreamReadCapability)'
	at com.fasterxml.jackson.datatype.joda.deser.DateTimeDeserializer._fromString(DateTimeDeserializer.java:111)
	at com.fasterxml.jackson.datatype.joda.deser.DateTimeDeserializer.deserialize(DateTimeDeserializer.java:53)

Tonight I will do some further digging and will keep you posted. Thanks for the support anyhow!

**Comment by efonsell** [comment]
Actually, we were able to reproduce the problem now. For some reason, having the jackson-databind in (nFlow root) dependency management with correct version does not affect the project depending on nflow-jetty. Adding this to your pom.xml should fix the problem:
```
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.12.0</version>
    </dependency>
```
We will also add this to nflow-jetty/pom.xml for the next release.

**Comment by mfdewit** [comment]
Good that you were able to reproduce this, your solution fixes the issue. Thanks!
No I can continue exploring this framework and test if it fits our needs :)
