### ISSUE TITLE
Unable to use timestamp with nflowObjectMapper

### ISSUE THREAD

**Issue by infraorder** [NitorCreations/nflow#506]
Hi there
been trying to get nflow working for a project however recently came into this issue when a class has a timestamp 
(This is using java11)

```INFO   | jvm 1    | 2022/03/01 14:25:21 | [2022-03-01 14:25:21.564] ERROR [qtp184873141-37] REMOVED - FooMethod  - General Exception - Failed to serialize value for fooVariable
INFO   | jvm 1    | 2022/03/01 14:25:21 | String: "Failed to serialize value for fooVariable"
INFO   | jvm 1    | 2022/03/01 14:25:21 | java.lang.RuntimeException: Failed to serialize value for fooVariable
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at io.nflow.engine.internal.workflow.ObjectStringMapper.convertFromObject(ObjectStringMapper.java:106)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at io.nflow.engine.workflow.instance.WorkflowInstance$Builder.putStateVariable(WorkflowInstance.java:470)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.ZonedDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: REMOVED)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer.serialize(UnsupportedTypeSerializer.java:35)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3821)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       at io.nflow.engine.internal.workflow.ObjectStringMapper.convertFromObject(ObjectStringMapper.java:104)
INFO   | jvm 1    | 2022/03/01 14:25:21 |       ... 108 common frames omitted
```
The class would have something similar to this:
`private LocalDate        expiryDate;`
Sorry if this is very vague.

Let me know if you need anything else.

**Comment by efonsell** [comment]
Try using [Joda-Time](https://www.joda.org/joda-time/) i.e. `org.joda.time.LocalDate` instead of `java.util.LocalDate`, nFlow has not migrated to JSR-310.

**Comment by gmokki** [comment]
Alternatively you can create your own ObjectMapper with `@Nflow` and `@Primary` annotations and add any type converters you need there. But remember to add also register the joda types, which nflow uses internally.

**Comment by infraorder** [comment]
@gmokki 
Sorry I don't quite follow what you mean by this

**Comment by infraorder** [comment]
Ended up doing @efonsell recommendation
